blogsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('historias/', include('historias.urls')),
    path('admin/', admin.site.urls),
]

historias/urls.py
from django.urls import path

from . import views

app_name = 'historias'


""""Urls para a primeira e segunda parte com views funcionais sem classes genericas"""
""""
urlpatterns = [
    path('', views.list_historias, name='index'),
    path('<int:historia_id>/', views.detail_historia, name='detail'),
    path('search/', views.search_historias, name='search'),
    path('create/', views.create_historia, name='create'),
    path('update/<int:historia_id>/', views.update_historia, name='update'),
    path('delete/<int:historia_id>/', views.delete_historia, name='delete'),

    path('', views.HistoriaListView.as_view(), name='index'),
] """


""""Mudanças das urls para a implantação das classes genéricas"""
urlpatterns = [
    path('', views.HistoriaListView.as_view(), name='index'),
    path('<int:pk>/', views.HistoriaDetailView.as_view(), name='detail'),
    path('search/', views.search_historias, name='search'),
    path('create/', views.HistoriaCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.HistoriaUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.HistoriaDeleteView.as_view(), name='delete'),
    path('<int:historia_id>/comment/', views.create_comment, name='comment'),
    path('categorias/', views.CategoriaListView.as_view(), name='categorias'),
    path('categorias/create', views.CategoriaCreateView.as_view(), name='createcategoria'),
    path('categorias/<int:pk>', views.historiascatego, name='indexcatego'),
]

historias/models.py
from django.db import models
from django.conf import settings


class Category(models.Model):
    nome = models.CharField(max_length=255)
    def __str__(self):
        return self.nome

class Historia(models.Model):
    name = models.CharField(max_length=255)
    capa = models.URLField(max_length=200, null=True)
    relato =models.CharField(max_length=5000)
    data = models.DateTimeField(auto_now=True)
    categoria = models.ManyToManyField(Category)
    def __str__(self):
        return f'{self.name} ({self.data})'
    
class Comment(models.Model):
    autor = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    texto = models.CharField(max_length=255)
    data = models.DateTimeField(auto_now=True)
    historia = models.ForeignKey(Historia, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.texto}" - {self.autor}'
    

historias/forms.py
from django.forms import ModelForm
from .models import Historia, Comment
from django import forms


class HistoriaForm(ModelForm):
    class Meta:
        model = Historia
        fields = ['name', 'capa','categoria', 'relato']
        labels = {
            'name':'Título da História Tenebrosa',
            'capa':'Quer adicionar uma ilustração de capa? (url)',
            'categoria':'Em quais categorias essa história se encaixa?        ',
            'relato':'Descreva todo o seu relato',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'autor',
            'texto',
        ]
        labels = {
            'autor': 'Usuário:',
            'texto': 'O que você tem a dizer?',
        }

historias/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Historia, Comment
from django.shortcuts import render, get_object_or_404


"""Primeira parte de implementação da views arquivos funcionais sem forms"""
"""def list_historias(request):
    historias_list = Historia.objects.all()
    context = {'historias_list': historias_list}
    return render(request, 'historias/index.html', context)"""

"""
def detail_historia(request, historia_id):
    historia = Historia.objects.get(pk=historia_id)
    context = {'historia': historia}
    return render(request, 'historias/detail.html', context)

def detail_historia(request, historia_id):
    historia = get_object_or_404(Historia, pk=historia_id)
    context = {'historia': historia}
    return render(request, 'historias/detail.html', context)
"""

def search_historias(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        historias_list = Historia.objects.filter(name__icontains=search_term)
        context = {"historias_list": historias_list}
    return render(request, 'historias/search.html', context)

"""
def update_historia(request, historia_id):
    historia = get_object_or_404(Historia, pk=historia_id)

    if request.method == 'POST':
        historia.name = request.POST['name']
        historia.data = request.POST['data']
        historia.capa = request.POST['capa']
        historia.relato = request.POST['relato']
        historia.save()
        return HttpResponseRedirect(
            reverse('historias:detail', args=(historia.id, )))

    context = {'historia': historia}
    return render(request, 'historias/update.html', context)
"""
"""
def delete_historia(request, historia_id):
    historia = get_object_or_404(Historia, pk=historia_id)

    if request.method == "POST":
        historia.delete()
        return HttpResponseRedirect(reverse('historias:index'))

    context = {'historia': historia}
    return render(request, 'historias/delete.html', context)
"""
"""Segunda parte de implementação da views arquivos funcionais com um forms"""
from .forms import HistoriaForm, CommentForm

"""
def create_historia(request):
    if request.method == 'POST':
        historia_name = request.POST['name']
        historia_data = request.POST['data']
        historia_capa = request.POST['capa']
        historia_relato = request.POST['relato']
        historia = Historia(name=historia_name,
                      data=historia_data,
                      capa=historia_capa,
                      relato=historia_relato)
        historia.save()
        return HttpResponseRedirect(
            reverse('historias:detail', args=(historia.id, )))
    else:
        form = HistoriaForm()
        context = {'form': form}
        return render(request, 'historias/create.html', context)
"""


"""Terceira parte com views genéricas"""
from django.views import generic
from django.urls import reverse_lazy

class HistoriaListView(generic.ListView):
    model = Historia
    template_name = 'historias/index.html'

class HistoriaDetailView(generic.DetailView):
    model = Historia
    template_name = 'historias/detail.html'

class HistoriaCreateView(generic.CreateView):
    model = Historia
    form_class = HistoriaForm
    template_name = 'historias/create.html'
    success_url = reverse_lazy('historias:index')

class HistoriaUpdateView(generic.UpdateView):
    model = Historia
    fields = ['name', 'capa', 'relato']
    template_name = 'historias/update.html'
    success_url = reverse_lazy('historias:index')

class HistoriaDeleteView(generic.DeleteView):
    model = Historia
    template_name = 'historias/delete.html'
    success_url = reverse_lazy('historias:index')

# Implementação dos comentarios nos posts
def create_comment(request, historia_id):
    historia = get_object_or_404(Historia, pk=historia_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            review_autor = form.cleaned_data['autor']
            review_texto = form.cleaned_data['texto']
            review = Comment(autor=review_autor,
                            texto=review_texto,
                            historia=historia)
            review.save()
            return HttpResponseRedirect(
                reverse('historias:detail', args=(historia_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'historia': historia}
    return render(request, 'historias/comment.html', context)

# Implementação das categorias nos posts
from .models import Category

class CategoriaListView(generic.ListView):
    model = Category
    template_name = 'historias/categorias.html'


class CategoriaCreateView(generic.CreateView):
    model = Category
    template_name = 'historias/createcategoria.html'
    fields = ['nome']
    success_url = reverse_lazy('historias:categorias')


def historiascatego(request, pk):
    historias_catego = Historia.objects.filter(categoria=pk)
    return render(request, 'historias/indexcatego.html', {'historiascatego': historias_catego})

historias/templates/historias/categorias.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias de Histórias</h2>

<section>
    {% for categoria in category_list %}
    <hr>
    <article>
        <div class="lista-de-cards">
            <div class="card">
                <a href="{% url 'historias:indexcatego' categoria.id %}">
                    <p>{{ categoria.nome}}</p>
                </a>
            </div>
        </div>
    </article>
    {% endfor %}
    <hr>
    <a href="{% url 'historias:createcategoria' %}"><button>Crie sua Categoria</button></a>
</section>

{% endblock content %}

historias/templates/historias/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Opa, bora desenvolver essa crítica construtiva sobre {{ historia.name }}</h2>

<form action="{% url 'historias:comment' historia.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar</button>
</form>

<p><a href="{% url 'historias:detail' historia.id %}">Desistiu? Bora voltar para  a história</a></p>
{% endblock content %}

historias/templates/historias/create.html
{% extends 'base.html' %} {% block content %}
<h2>Compartilhe o seu relato com a gente!</h2>
<form method="POST" action="{% url 'historias:create' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Postar!</button>
</form>

{% endblock content %}

historias/templates/historias/createcategoria.html
{% extends 'base.html' %}

{% block title %}
Criar Categoria
{% endblock title %}

{% block content %}
<h2>Criar Nova Categoria</h2>

<form action="{% url 'historias:createcategoria' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

historias/templates/historias/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'historias:delete' historia.id %}" method="post">
  {% csrf_token %}
  <p>
    Você tem certeza que deseja apagar "{{ historia.name }}"?
  </p>
  
  <button type="submit">Apagar</button>

  <p>Talvez esses segredos realmente devam retornar às profundezas</p>
</form>
{% endblock content %}

historias/templates/historias/detail.html
{% extends 'base.html' %} {% block title %} {{ historia.name }} ({{
    historia.data }} {% endblock title %} {% block content %}
    <h1>{{ historia.name }}</h1>
    
    <section class="dados-de-filme">
      <img src="{{ historia.capa }}" alt="capa {{ historia.name}}" />
      <ul>
        <li> <b>Data de Publicação:</b> {{ historia.data }}</li>
        <li><a href="{% url 'historias:update' historia.id %}">Editar</a></li>
        <li><a href="{% url 'historias:delete' historia.id %}">Apagar</a></li>
      </ul>
      <ul>
        Categorias:
        {% for cat in historia.categoria.all %}
         <li><a href="{% url 'historias:indexcatego' pk=cat.id %}">    {{ cat.nome }}</a></li>
        {% endfor %}
      </ul>
    </section>
    <section class="desc-relato">
      {{ historia.relato }}
    </section>
    <hr>
  <section>
      <header>
          <h3>Comentários, Pitacos e Desabafos:</h3>
      </header>
      <ul>
          {% if historia.comment_set.all %}
              {% for comment in historia.comment_set.all reversed%}
                  <section class="cardcom">
                          "{{ comment.texto }}"
                      <figcaption>—{{ comment.autor }} ({{ comment.data }})</figcaption>
                    </section>
              {% endfor %}
          {% else %}
              <p>Essa história deixou todos sem palavras até o momento. O chupa cabra também comeu a sua língua?</p>
          {% endif %}
      </ul>
  </section>
  <hr>
  <hr>
    <h3>Achou algo muito estranho ou interessante?</h3>
    <a href="{% url 'historias:comment' historia.pk %}"><button>Quer dar um Pitaco?</button></a>
    
    {% endblock content %}

historias/templates/historias/index.html
{% extends 'base.html' %} {% block content %}
<h2>Todas as Histórias</h2>
<section>
    <p>
      Procurando algo específico? <a href="{% url 'historias:search' %}">Clica aqui!</a>
    </p>
    <p>
        Não encontrou nenhum relato?
        <a href="{% url 'historias:create' %}">Adicione o seu!</a>
      </p>
</section>

{% if historia_list %}
<section class="lista-de-cards">
  {% for historia in historia_list %}
  <article class="card">
    <a href="{% url 'historias:detail' historia.id %}">
      <img src="{{ historia.capa }}" alt="Imagem de capa {{ historia.name}}"
    /></a>
    <p>{{ historia.name }}</p>
  </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrada nenhuma história com esse nome. Você pode publicar a sua!</p>
{% endif %} {% endblock content %}

historias/templates/historias/indexcatego.html
{% extends 'base.html' %} {% block content %}
<h2>Todas as Histórias nessa categoria são:</h2>

<section>
    <p>
      Procurando algo mais especificamente? <a href="{% url 'historias:search' %}">Clica aqui!</a>
    </p>
    <p>
        Não encontrou nenhum relato interessante nessa categoria?
        <a href="{% url 'historias:create' %}">Adicione o seu!</a>
      </p>
</section>


{% if historiascatego %}
<section class="lista-de-cards">
  {% for historia in historiascatego %}
  <article class="card">
    <a href="{% url 'historias:detail' historia.id %}">
      <img src="{{ historia.capa }}" alt="Imagem de capa {{ historia.name}}"
    /></a>
    <p>{{ historia.name }}</p>
  </article>
  {% endfor %}
</section>


{% else %}
<p>Não foi encontrada nenhuma história nessa categoria. Você pode publicar a primeira!</p>
{% endif %}

{% endblock content %}

historias/templates/historias/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Procure alguma História Aterrorizante</h2>
<form action="{% url 'historias:search' %}">
    <p>
        <label for="id_query">O que buscas?</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>

{% if historia_list %}
<section class="lista-de-cards">
    {% for historia in historia_list %}
    <article class="card">
        <img src="{{ historia.capa }}" alt="capa{{ historia.name }}">
        <p>{{ historia.name }} ({{ historia.data }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Vixe, não tem nada com esse nome ainda. Talvez algum ser maligno tenha apagado!</p>
{% endif %}

{% endblock content %}

historias/templates/historias/update.html
{% extends 'base.html' %}
{% block content %}
<h2>Atualizar Dados da História {{ historia.name }}</h2>
<form method="post" action="{% url 'historias:update' historia.id%}">
  {% csrf_token %}
  <p>
    <label for="id_name">Título: </label>
    <input type="text" name="name" id="id_name" value="{{ historia.name }}" />
</p>
  <p>
    <label for="id_data">Data:</label>
    <input
      type="text"
      name="data"
      id="id_data"
      value="{{ historia.data }}"
    />
</p>
  <p>
    <label for=" id_capa">URL da capa: </label>
    <input
      type="url"
      name="capa"
      id="id_capa"
      value="{{historia.capa}}"
    />
</p>
<p>
    <label for="id_relato">Relato:</label>
    <input
      type="text"
      name="relato"
      id="id_relato"
      value="{{ historia.relato }}"
    />
</p>

  <button type="submit">Atualizar </button>
</form>
{% endblock content %}