blogsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('historias/', include('historias.urls')),
    path('admin/', admin.site.urls),
]

historias/urls.py
from django.urls import path

from . import views

app_name = 'historias'


""""Urls para a primeira e segunda parte com views funcionais sem classes genericas"""
""""
urlpatterns = [
    path('', views.list_historias, name='index'),
    path('<int:historia_id>/', views.detail_historia, name='detail'),
    path('search/', views.search_historias, name='search'),
    path('create/', views.create_historia, name='create'),
    path('update/<int:historia_id>/', views.update_historia, name='update'),
    path('delete/<int:historia_id>/', views.delete_historia, name='delete'),

    path('', views.HistoriaListView.as_view(), name='index'),
] """


""""Mudanças das urls para a implantação das classes genéricas"""
urlpatterns = [
    path('', views.HistoriaListView.as_view(), name='index'),
    path('<int:pk>/', views.HistoriaDetailView.as_view(), name='detail'),
    path('search/', views.search_historias, name='search'),
    path('create/', views.HistoriaCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.HistoriaUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.HistoriaDeleteView.as_view(), name='delete'),
    path('<int:historia_id>/comment/', views.create_comment, name='comment'),
    path('categorias/', views.CategoriaListView.as_view(), name='categorias'),
    path('categorias/create', views.CategoriaCreateView.as_view(), name='createcategoria'),
    path('categorias/<int:pk>', views.historiascatego, name='indexcatego'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Blogueiros do Além!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}"> </a> 
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'historias:index' %}">Histórias</a></li>
                <li><a href="{% url 'historias:categorias' %}">Categorias</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright Assombra e Ação 2024</small>
        </p>
    </footer>
</body>

</html>